---
# tasks file for docker-registry

- name: login
  docker_login:
    username: "amaniattia"
    password: "chiheb25815131"
    reauthorize: yes
- name: docker push
  docker_image:
    name: appfront:latest
    repository: amaniattia/devops
    push: yes
    source: local 
